name: python-fr
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - setuptools
  - black
  - numpy
  - matplotlib
  - pillow
  - jupyter
  - nbconvert
  - jupytext
  - pandoc
  - pip:
    - pygame
    - pandoc==2.1

